include: package:flutter_lints/flutter.yaml

linter:
  rules:
    - always_declare_return_types
    - avoid_print
    - prefer_single_quotes
    - sort_pub_dependencies
    - lines_longer_than_80_chars
